apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "casdoor.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "casdoor.labels" . | nindent 4 }}
data:
  RUNNING_IN_DOCKER: {{ .Values.environments.runing_in_docker | quote }}