
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gc-wms-pv-nas
  labels:
    alicloud-pvname: gc-wms-pv-nas
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteMany
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeHandle: gc-wms-pv-nas
    volumeAttributes:
      server: {{ .Values.pv.flexVolume.server }}
      path: {{ .Values.pv.flexVolume.path }}
  mountOptions:
  - nolock,tcp,noresvport
  - vers=3