kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gc-wms-pvc-nas
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  selector:
    matchLabels:
      alicloud-pvname: gc-wms-pv-nas